### ISSUE TITLE
Shoutem cli install error

### ISSUE THREAD

**Issue by mikev10** [shoutem/cli#21] opened 2017-08-25 14:58 UTC
I am trying to follow the steps listed [here](https://shoutem.github.io/docs/extensions/tutorials/getting-started) but keep getting an error when trying to install `shoutem-cli - $ npm install -g @shoutem/cli`

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngrok@2.2.21 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ngrok@2.2.21 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                     ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-24T13_20_31_973Z-debug.log
```

The log file can be found [here](https://gist.github.com/mikev10/9589151299ead7b85afed0117df27e7c).

I'm not sure where to begin so any help would be greatly appreciated.

Thanks!

**Comment by mikev10** [comment] 2017-08-28 19:04
Any help would be great.

**Comment by Vladimir-Vdovic** [comment] 2017-08-29 06:19
Which OS are you using?

What version of NPM and Node.js are you using?

I'll try to reproduce this and see if I can find a workaround.

**Comment by mikev10** [comment] 2017-08-29 16:50
I am using a cloud server.
OS: Ubuntu 16.04
Node.js: v6.11.1
NPM: v5.3.0

**Comment by dodsky** [comment] 2017-08-29 21:16
I've managed to reproduce this issue now with all this environment info. As far as I can tell it's related to `npm@5.3.0` and Unix environment (OSX, Ubuntu). It's working on Windows machines with latest `npm`. While we investigate this further, as a workaround I can suggest downgrading to latest 4.x version of `npm` by running `npm install -g npm@4`. Verify npm version with `npm -v`. After downgrade, run `sudo npm uninstall @shoutem/cli -g` to get to a clean state, and then run `npm install @shoutem/cli -g` again.

**Comment by mikev10** [comment] 2017-08-29 23:42
That worked! Thank you so much for your help.

Should I be worried about this error during the install:
```
{ Error: EACCES: permission denied, unlink '/root/.shoutem/mobile-env'
    at Error (native)
  errno: -13,
  code: 'EACCES',
  syscall: 'unlink',
  path: '/root/.shoutem/mobile-env' }
/usr/lib
```

Also, the version is 0.9.5. Can you confirm if this is the right version?

**Comment by Vladimir-Vdovic** [comment] 2017-09-07 08:39
0.9.6 is the active version of the Shoutem CLI, it doesn't contain any breaking changes compared to 0.9.5 to the issue at hand, so I wouldn't worry about the discrepancy.

Main issue seems to be resolved, closing the issue.

**Closed by Vladimir-Vdovic** 2017-09-07 08:39 UTC

**Comment by reza7rm** [comment] 2018-03-17 09:47
I am still encountering the issue and I don't think downgrading npm is a real solution as it impacts on other projects needing npm to be updated

**Comment by sengard** [comment] 2019-06-20 19:18
This one did the trick for me:

```
sudo  npm  i  -g @shoutem/cli --unsafe-perm=true --allow-root
```

_Originally posted by @rodrigocam in https://github.com/bubenshchykov/ngrok/issues/140#issuecomment-482856609_
